version: "2"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
    MYSQL_ROOR_PASSWORD: root
  volumes:
   - /home/mysql/data:/var/lib/mysql
 spring_app:
  image: achatproject
  container_name : achatproject
  restart: on-failure
  ports:
    - 9090:9090
  depends_on:
    - mysqldb
    
    
 Sonarqube:
  image: sonarqube:8.9.7-community
  ports:
   - "9000:9000"
   - "9092:9092"
  volumes:
   - 'sonarQube_data:/opt/SonarQube/data'
   - 'sonarQube_extensions:/opt/SonarQube/extensions'
   - 'sonarQube_logs:/opt/SonarQube/logs'
  
 nexus:
  image: sonatype/nexus3
  ports:
   - "8081:8081"
  volumes:
   - "nexus-data:/sonatype-work"

volumes:
 sonarQube_data:
 sonarQube_extensions:
 sonarQube_logs:
 nexus-data: