version: "2"

services:
 mysqldb:
   image: "mysql:5.6"
   environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=offre
   ports:
      - 3308:3306
 app:
   container_name: spring
   image: "spring"
   depends_on:
     - mysqldb
   build: .
   restart: on-failure
   ports:
     - "8089:8089"
   environment:
     SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachato?useSSL=false",
       "spring.datasource.username" : "root",
       "spring.datasource.password" : "root",
       "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
       "spring.jpa.hibernate.ddl-auto" : "update"}'
   stdin_open: true
   tty: true
    
    
 

volumes:
 db: